Repository WordPress/wordcamp.org, pull requests merged in 2020-08, with the labels that each got.

#535 Ignore Query Monitor plugin
  .gitignore
Labels: [Component] Tooling, [Status] Needs Decision, [Type] Enhancement

#544 Coming Soon Page: If WordCamp cancelled, replace the date with "Cancelled" text and remove Jetpack subscription form
  public_html/wp-content/plugins/wordcamp-coming-soon-page/classes/wordcamp-coming-soon-page.php
  public_html/wp-content/plugins/wordcamp-coming-soon-page/views/template-coming-soon.php
Labels: [Priority] 1, [Status] Needs Review

#549 Plugins: Add `permission_callback` to API registration
  public_html/wp-content/mu-plugins/lets-encrypt-helper.php
  public_html/wp-content/plugins/wc-post-types/inc/rest-api.php
  public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php
  public_html/wp-content/plugins/wordcamp-site-cloner/wordcamp-site-cloner.php
Labels: [Status] Ready to Merge, [Type] Bug

#548 Coming Soon mode: use edit_theme_options as required capability instead of administrator role
  public_html/wp-content/plugins/wordcamp-coming-soon-page/classes/wccsp-settings.php
Labels: [Component] Capabilities, [Priority] 3, [Status] Ready to Merge, [Type] Bug

#512 Post Types: Add gutenberg support on speaker & organizer post types
  public_html/wp-content/mu-plugins/gutenberg-tweaks.php
  public_html/wp-content/plugins/wc-post-types/css/editor.css
  public_html/wp-content/plugins/wc-post-types/inc/rest-api.php
  public_html/wp-content/plugins/wc-post-types/js/src/components/date-control/index.js
  public_html/wp-content/plugins/wc-post-types/js/src/components/hooks/use-post-meta.js
  public_html/wp-content/plugins/wc-post-types/js/src/components/username-control/index.js
  public_html/wp-content/plugins/wc-post-types/js/src/organizer/index.js
  public_html/wp-content/plugins/wc-post-types/js/src/organizer/panel-info.js
  public_html/wp-content/plugins/wc-post-types/js/src/session/panel-info/date.js
  public_html/wp-content/plugins/wc-post-types/js/src/session/panel-info/index.js
  public_html/wp-content/plugins/wc-post-types/js/src/speaker/index.js
  public_html/wp-content/plugins/wc-post-types/js/src/speaker/panel-info.js
  public_html/wp-content/plugins/wc-post-types/package.json
  public_html/wp-content/plugins/wc-post-types/wc-post-types.php
Labels: [Component] WC-Post-Types, [Status] Ready to Merge

#536 Application tracker improvements
  public_html/wp-content/plugins/wcpt/views/common/metabox-original-application.php
  public_html/wp-content/plugins/wcpt/views/wordcamp/metabox-original-application.php
  public_html/wp-content/plugins/wcpt/wcpt-event/class-event-admin.php
  public_html/wp-content/plugins/wcpt/wcpt-meetup/class-meetup-admin.php
  public_html/wp-content/plugins/wcpt/wcpt-meetup/class-meetup-application.php
  public_html/wp-content/plugins/wcpt/wcpt-wordcamp/wordcamp-admin.php
Labels: [Component] WCPT, [Status] Ready to Merge, [Type] UX Improvement
