Repository WordPress/wordcamp.org, pull requests merged in 2022-05, with the labels that each got.

#767 CampTix: Remove camptix-mercadopago from Docker composer.json
  .docker/config/composer.json
Labels: [Component] Tooling

#768 Fix wordcamp.test success message
  .docker/readme.md
Labels: [Status] Needs Review, [Component] Tooling

#774 CampTix: Ensure camptix scripts are loaded in the footer
  public_html/wp-content/mu-plugins/camptix-tweaks/addons/class-payment-options.php
  public_html/wp-content/plugins/camptix-invoices/admin/js/camptix-invoices.js
Labels: [Component] CampTix
